### ISSUE TITLE
When neither demo data nor talk uploading is used, talk assignments are not saved

### ISSUE THREAD

**Issue by fabrice102** [kaymckelly/program-editor#115]
To see this problem, create a new program without demo data and only with manually entered talks.
Then, talk assignments are not saved.

(You can see some logs on the JS console.)

A dirty workaround consists in uploading some talks and then removing them. E.g., using the following file (from https://www.iacr.org/tools/program/docs/help.html):

```
{
    "acceptedPapers": [
        {
            "title": "Title of first paper",
            "authors": "Alan Turing and Aaron Aardvark",
            "affiliations": "Princeton University; Harvard University",
            "category": "Theory"
        },
        {
            "title": "New Directions in Cryptography",
            "authors": "Whitfield Diffie and Martin E.Hellman",
            "affiliations": "Stanford University",
            "category": "Public Key Cryptography"
        }
    ]
}
```

**Comment by kaymckelly** [comment]
Good catch! This is a pretty serious issue, so it's gonna take some time to debug. It appears the drag and drop doesn't work for talks created this way. Either findObj is not working or it's not getting the correct arguments.

**Comment by kaymckelly** [comment]
Solved!
