### ISSUE TITLE
Add Handlebars custom helper to...

### ISSUE THREAD

**Issue by kaymckelly** [kaymckelly/program-editor#31]
simplify template by testing whether there's two sessions in a single time slot, then given alternative code for dual-track there instead of in the template proper

**Comment by kaymckelly** [comment]
Significantly more complicated than first thought; will make individual elements hard to read. If statements will need to define classes for each div. May have a way around by making CSS conditional, which then renders it harder to read.

**Comment by kmccurley** [comment]
There is a helper that supports Array.equalsLength that could be used for this, but I don't want to drag in 188 helpers just to get this one. See [this site](https://github.com/helpers/handlebars-helpers/blob/master/lib/array.js#L313).

**Comment by kaymckelly** [comment]
Unclear what we were trying to solve with this.
