### ISSUE TITLE
The progData object needs a name parameter (a string)

### ISSUE THREAD

**Issue by kmccurley** [kaymckelly/program-editor#36]
The progData needs a name, e.g., "Crypto 2017" that will be used to recognize it. It should be at the top level of the object. See http://www.iacr.org/cryptodb/pc/program/crypto_config.json for an example. I have already added this to the schema.

**Comment by kaymckelly** [comment]
Fixed via commit 3643eb8be6d81ebe78676e3833add815ccc030ae
