### ISSUE TITLE
lastTalkIndex needs to be part of progData (and saved)

### ISSUE THREAD

**Issue by kmccurley** [kaymckelly/program-editor#46]
I noticed that when you load an existing program and then insert a new talk, lastTalkIndex has not been initialized, and would have to be created from the existing IDs on talks. If you load an existing program and then add a talk, lastTalkIndex is undefined. Another way to do this is to reassign IDs to talks when they are loaded and calculate lastTalkIndex (so we don't have to save it with the config).

**Comment by kaymckelly** [comment]
Potentially linked with issue #47?

**Comment by kaymckelly** [comment]
In fact was not linked with issue 47

**Comment by kaymckelly** [comment]
solved by  [commit #98d1f8f59abafdd37bd26669596d278cbff44587](https://github.com/kaymckelly/program-editor/commit/98d1f8f59abafdd37bd26669596d278cbff44587)
