### ISSUE TITLE
Skip upload talks

### ISSUE THREAD

**Issue by kaymckelly** [kaymckelly/program-editor#48]
option to skip uploading talks during setup and either add manually via add talk button (one by one, would be ok for a one day workshop or similar) or to upload entire json of accepted talks later in process)

**Comment by kaymckelly** [comment]
Would also need to check existing talks to make sure duplicates are not added. Will require some kind of hashing scheme.

**Comment by kmccurley** [comment]
This is one reason why I advocate having a menu with an action to add websubrev talks later.

**Comment by kmccurley** [comment]
I added the button to skip websubrev upload in [this change](https://github.com/kaymckelly/program-editor/commit/ead8d887723e47a878cc9509dc813ad5438516c5).
