### ISSUE TITLE
Use partial to define talk template in only one place

### ISSUE THREAD

**Issue by kaymckelly** [kaymckelly/program-editor#53]
See [here](http://blog.teamtreehouse.com/handlebars-js-part-2-partials-and-helpers) for more info on Handlebars partial. Will solve issue of different styling of talks once dragged from talks list to schedule. DO NOT attempt to solve in a branch with other changes; stick it in its' own branch.

**Comment by kmccurley** [comment]
This turned out to be pretty easy. See [this change](https://github.com/kaymckelly/program-editor/commit/7b29e3c5b922b38eb3205f22a673609e537c8f36)
