### ISSUE TITLE
Delete session button nonfunctional

### ISSUE THREAD

**Issue by kaymckelly** [kaymckelly/program-editor#56]
While it gives warnings locally about "are you sure want to delete a session?", it doesn't appear to actually do anything once those warnings are dismissed.

**Comment by kmccurley** [comment]
This was [fixed](https://github.com/kaymckelly/program-editor/commit/d663e8a892040887e609e8fed3ca56f4f12bbaba). The tricky part was that we can't just identify a session by it's ID: we need to apply splice on the sessions array of the relevant timeslot.
