### ISSUE TITLE
Callback for time slot editing

### ISSUE THREAD

**Issue by kaymckelly** [kaymckelly/program-editor#58]
Need callback when submit is hit on the edit time slot so that:

- min time for first session of day is not set
- max time for last session of day is not set (will check against length of array)

**Comment by kmccurley** [comment]
Editing a timeslot was implemented in [this change](https://github.com/kaymckelly/program-editor/commit/6f40556893487a989410d96878dbfcb1dcde7e50). Now the user can add a second session if there is only one, and change the start and end time in any event. Once a change is made, the timeslots for a day are resorted by start time.
