### ISSUE TITLE
Add menu for actions and help

### ISSUE THREAD

**Issue by kmccurley** [kaymckelly/program-editor#65]
We need to have menu items for the actions of "Start new program" and "Upload from websubrev". In addition we should have links to help, and an "About this editor" link.

**Comment by kmccurley** [comment]
This menu was now added, but it still needs some work.
1. the upload from websubrev menu item should only be active when a program is showing.
2. the help files need considerable work.
3. the "About this program" should point to a more informative page that links to github.

**Comment by kmccurley** [comment]
The menu UI could use some improvment, but it now uses the same UI whether you upload at the beginning or later on. Changing priority to medium.

**Comment by kaymckelly** [comment]
Fixed
