### ISSUE TITLE
Displaying alerts when one modal is already open

### ISSUE THREAD

**Issue by kaymckelly** [kaymckelly/program-editor#80]
Currently using window.confirm but I dislike the lack of styling/fact that it's gray so is easier to overlook (also does not gray out the background as other options would).

Accessibility requirements are such that we must either have:
- error alert then focus (e.g. windows.confirm)
- errors on top (e.g. modal has hidden div at top that displays errors when found)
- inline errors (e.g. marking errors in modal inline --> unlikely to be useful for our use case)
[See here for more info](http://webaim.org/techniques/formvalidation/#error)

For cases in which a modal (e.g. edit talk, add time slot, etc) is already open:

- option 1: layer modals, with the standard error box overlaying the currently open modal. "ok" triggers a save/whatever forbidden action you were trying, "cancel" returns to original modal to allow user to make a different choice. [see here for example](http://jsfiddle.net/CxdUQ/)
- option 2: mark errors at top of modal using alerts, requires users to click save again (which can only be done after dismissing alert, to ensure comprehension?)

Rejected options:

- JS alerts; they are only dismissible rather than offering some sort of interactive option
- .prompt; would require user to type an accepted phrase to confirm forbidden action, reduces ease of use beyond what it reasonable

**Comment by kaymckelly** [comment]
After design discussion, we decided to insert an alert above the red delete button/after the HR, stretching across the modal. Also change button text to confirm delete.

**Comment by kmccurley** [comment]
This was fixed in [this pull request](https://github.com/kaymckelly/program-editor/pull/87) by showing an alert when you click on delete, and changing the text on the button.
