### ISSUE TITLE
Editing of talks was broken

### ISSUE THREAD

**Issue by kmccurley** [kaymckelly/program-editor#98]
[This change](https://github.com/kaymckelly/program-editor/commit/7939381af0aee528c571041dc3db417969533ae5#diff-eacf331f0ffc35d4b482f1d15a887d3b) introduced a bug by removing the partial for the talk editor. You can no longer edit an existing talk.

This change was too big and should have been pruned to a set of independent changes.

**Comment by kaymckelly** [comment]
Unable to replicate
